/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarAssembly;

import CarAssembly.Decorators.Clime;
import CarAssembly.Decorators.HeatedSeat;
import CarAssembly.Decorators.Hp;
import CarAssembly.Decorators.Rims;
import CarAssembly.Decorators.WeightReduction;

/**
 *
 * @author Feri
 */
public class CustomFrame extends javax.swing.JFrame {
    
    Logger log = Logger.getInstance();
    private CarBase car;
    
    public void Details(CarBase car){
        jLabelShift.setText("Shift: "+car.getShift());
        jLabelDoors.setText("Doors: "+ car.getDoors());
        jLabelHp.setText("HP: "+ car.getHp());
        jLabelCc.setText("cc: "+ car.getCc());
        jLabelWeight.setText("Weight: "+car.getWeight());
        jLabelSeats.setText("Seats: "+ car.getSeats());
        jLabelFuel.setText("Fuel: "+ car.getFuel());
        jLabelPrice.setText("Price: " + car.getPrice());
    }
    /**
     * Creates new form NewJFrame
     */
    public CustomFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxClime = new javax.swing.JCheckBox();
        jCheckBoxHp = new javax.swing.JCheckBox();
        jCheckBoxWeight = new javax.swing.JCheckBox();
        jCheckBoxRims = new javax.swing.JCheckBox();
        jCheckBoxHeatedSeat = new javax.swing.JCheckBox();
        jButtonOrder = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jComboBoxHp = new javax.swing.JComboBox<>();
        jComboBoxWeight = new javax.swing.JComboBox<>();
        jComboBoxRims = new javax.swing.JComboBox<>();
        jLabelCar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelHp = new javax.swing.JLabel();
        jLabelWeight = new javax.swing.JLabel();
        jLabelFuel = new javax.swing.JLabel();
        jLabelCc = new javax.swing.JLabel();
        jLabelDoors = new javax.swing.JLabel();
        jLabelShift = new javax.swing.JLabel();
        jLabelSeats = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 300));

        jComboBoxCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Opel", "Nissan", "BMW" }));
        jComboBoxCar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCarItemStateChanged(evt);
            }
        });

        jLabel1.setText("Extras:");

        jLabel2.setText("Car:");

        jCheckBoxClime.setText("Clime");

        jCheckBoxHp.setText("HP");

        jCheckBoxWeight.setText("kg");

        jCheckBoxRims.setText("col");

        jCheckBoxHeatedSeat.setText("Heated seat");

        jButtonOrder.setText("Next");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonHome.setText("Back");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jComboBoxHp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "50", "100", "150" }));
        jComboBoxHp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHpItemStateChanged(evt);
            }
        });

        jComboBoxWeight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "30", "90", "160" }));
        jComboBoxWeight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxWeightItemStateChanged(evt);
            }
        });

        jComboBoxRims.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16", "17", "18", "19" }));
        jComboBoxRims.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRimsItemStateChanged(evt);
            }
        });

        jLabelCar.setText("-");

        jLabel4.setText("Details:");

        jLabelHp.setText("HP:");

        jLabelWeight.setText("Weight:");

        jLabelFuel.setText("Fuel:");

        jLabelCc.setText("cc:");

        jLabelDoors.setText("Doors:");

        jLabelShift.setText("Shift:");

        jLabelSeats.setText("Seats:");

        jLabelPrice.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxCar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelShift, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxClime)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBoxHp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBoxWeight, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBoxRims, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxRims, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jCheckBoxWeight))
                                            .addComponent(jCheckBoxHp)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBoxHeatedSeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDoors, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCc)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabelHp)
                            .addComponent(jLabelWeight)
                            .addComponent(jLabelFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(352, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCar)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxHp)
                        .addComponent(jComboBoxHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelHp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxWeight)
                    .addComponent(jComboBoxWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRims)
                    .addComponent(jComboBoxRims, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelShift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxHeatedSeat)
                    .addComponent(jLabelFuel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxClime)
                    .addComponent(jLabelCc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDoors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jLabelSeats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonOrder))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelHp.getAccessibleContext().setAccessibleName("jLabelHp");
        jLabelWeight.getAccessibleContext().setAccessibleName("jLabelWeight");
        jLabelFuel.getAccessibleContext().setAccessibleName("jLabelFuel");
        jLabelCc.getAccessibleContext().setAccessibleName("jLabelCc");
        jLabelDoors.getAccessibleContext().setAccessibleName("jLabelDoors");
        jLabelShift.getAccessibleContext().setAccessibleName("jLabelShift");
        jLabelSeats.getAccessibleContext().setAccessibleName("jLabelSeats");
        jLabelPrice.getAccessibleContext().setAccessibleName("jLabelPrice");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCarItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED) {
        //Do any operations you need to do when an item is selected.
    
        if(jComboBoxCar.getSelectedIndex() == 0)
        {   
            //car = new Car("Nissan","Silvia", "Manual", 1, 2, 4, 12, 1, "Gasoline");
            //String Brand, String model, String shift, int doors, int hp, int cc, int weight, int seats, String fuel, int Price
        }
        if(jComboBoxCar.getSelectedIndex() == 1)
        {
            car = new Car("Opel","Astra", "Manual", 5, 95, 1600, 1400, 5, "Gasoline", 5000);
            Details(car);
        }
        if(jComboBoxCar.getSelectedIndex() == 2)
        {
            car = new Car("Nissan","Skyline GT-R", "Manual", 3, 320, 3000, 1600, 2, "Gasoline", 60000);
            Details(car);
        }
        if(jComboBoxCar.getSelectedIndex() == 3)
        {
            car = new Car("BMW","M3 E36", "Manual", 3, 240, 2500, 1500, 4, "Gasoline", 10000);
            Details(car);
            
        }
        jLabelCar.setText(car.print());
        } 
        else if(evt.getStateChange() == evt.DESELECTED){
            jComboBoxHp.setSelectedIndex(0);
            jComboBoxWeight.setSelectedIndex(0);
            jComboBoxRims.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_jComboBoxCarItemStateChanged

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        HomeFrame home = new HomeFrame();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxHp.isSelected()){
            car = new Hp(car, Integer.parseInt(jComboBoxHp.getItemAt(jComboBoxHp.getSelectedIndex())));
        }
        if(jCheckBoxWeight.isSelected()){
            car = new WeightReduction(car, Integer.parseInt(jComboBoxWeight.getItemAt(jComboBoxWeight.getSelectedIndex())));
        }
        if(jCheckBoxRims.isSelected()){
            car = new Rims(car, Integer.parseInt(jComboBoxRims.getItemAt(jComboBoxRims.getSelectedIndex())));
        }
        if(jCheckBoxHeatedSeat.isSelected()){
            car = new HeatedSeat(car);
        }
        if(jCheckBoxClime.isSelected()){
            car = new Clime(car);
        }
        //log.logOrder(car.print(), car.getPrice());
        
        OrderFrame order = new OrderFrame(car);
        order.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jComboBoxHpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHpItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxHpItemStateChanged

    private void jComboBoxWeightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxWeightItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxWeightItemStateChanged

    private void jComboBoxRimsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRimsItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxRimsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JCheckBox jCheckBoxClime;
    private javax.swing.JCheckBox jCheckBoxHeatedSeat;
    private javax.swing.JCheckBox jCheckBoxHp;
    private javax.swing.JCheckBox jCheckBoxRims;
    private javax.swing.JCheckBox jCheckBoxWeight;
    private javax.swing.JComboBox<String> jComboBoxCar;
    private javax.swing.JComboBox<String> jComboBoxHp;
    private javax.swing.JComboBox<String> jComboBoxRims;
    private javax.swing.JComboBox<String> jComboBoxWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCar;
    private javax.swing.JLabel jLabelCc;
    private javax.swing.JLabel jLabelDoors;
    private javax.swing.JLabel jLabelFuel;
    private javax.swing.JLabel jLabelHp;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelSeats;
    private javax.swing.JLabel jLabelShift;
    private javax.swing.JLabel jLabelWeight;
    // End of variables declaration//GEN-END:variables
}
